[package]
name = "aoc19"
version = "0.1.0"
authors = ["ocboogie <boogie@mikulec.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aoc-runner = "*"
aoc-runner-derive = "0.2.2"
